module Lasp
  CORELIB = {
    :+          => -> (*args)         { args.reduce(:+)                            },
    :-          => -> (*args)         { args.reduce(:-)                            },
    :*          => -> (*args)         { args.reduce(:*)                            },
    :/          => -> (*args)         { args.reduce(:/)                            },
    :<          => -> (*args)         { args.each_cons(2).all? { |a, b| a < b  }   },
    :>          => -> (*args)         { args.each_cons(2).all? { |a, b| a > b  }   },
    :<=         => -> (*args)         { args.each_cons(2).all? { |a, b| a <= b }   },
    :>=         => -> (*args)         { args.each_cons(2).all? { |a, b| a >= b }   },
    :"="        => -> (*args)         { args.uniq.count == 1                       },
    :list       => -> (*args)         { args                                       },
    :head       => -> (list)          { list.first                                 },
    :tail       => -> (list)          { list.drop(1)                               },
    :cons       => -> (item, list)    { [item] + list                              },
    :dict       => -> (*args)         { Hash[*args]                                },
    :get        => -> (key, a)        { a[key]                                     },
    :assoc      => -> (dst, key, val) { dst.dup.tap { |d| d[key] = val  }          },
    :dissoc     => -> (dst, key)      { dst.dup.tap { |d| d.delete(key) }          },
    :not        => -> (arg)           { !arg                                       },
    :print      => -> (*output)       { STDOUT.print(*output)                      },
    :readln     => -> ()              { STDIN.gets.chomp                           },
    :apply      => -> (f, list)       { f.call(*list)                              },
    :send       => -> (m, o, *args)   { o.public_send(m, *args)                    },
  }.freeze
end
